import type { Metadata } from 'next';
import React from 'react';

import { LocaleProvider } from '@/shared/lib/locale-provider';
import { MainLayout } from '@/widgets';

type LayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <LocaleProvider>
      <MainLayout>{children}</MainLayout>
    </LocaleProvider>
  );
}
